{% set name = "raven" %}
{% set version = "6.5.0" %}
{% set sha256 = "84da75114739191bdf2388f296ffd6177e83567a7fbaf2701e034ad6026e4f3b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  entry_points:
    - raven = raven.scripts.runner:main

requirements:
  build:
    - python
    - setuptools
    - contextlib2
  run:
    - python
    - certifi
    - contextlib2

test:
  imports:
    - raven
    - raven.conf
    - raven.handlers
    - raven.scripts
    - raven.transport
    - raven.utils
    - raven.utils.serializer

  commands:
    - raven --help

about:
  home: https://github.com/getsentry/raven-python
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Raven is a client for Sentry (https://getsentry.com)'

  description: |
    Raven is a Python client for Sentry. It provides full out-of-the-box
    support for many of the popular frameworks, including Django, and Flask.
    Raven also includes drop-in support for any WSGI-compatible web
    application.
  doc_url: https://docs.sentry.io/clients/python/
  dev_url: https://github.com/getsentry/raven-python

extra:
  recipe-maintainers:
    - gqmelo
